services:
  racecast:
    build: .
    image: racecast
    container_name: racecast
    restart: unless-stopped
    env_file:
      - .env
    privileged: true
    devices:
      - /dev:/dev
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
