name: Building project

on:
    pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    dependencies:
        name: Dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install dependencies
              run: bun install

    build:
        name: Build
        needs: dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Build project
              run: bun run build
